######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 24 14:28:29 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h ../src/com.h ../src/LinuxMsg.h
FORMS += mainwindow.ui \
    mainwindow_zigbee_test.ui
SOURCES += main.cpp mainwindow.cpp ../src/com.cpp ../src/LinuxMsg.cpp

